FROM python:3.11-slim

WORKDIR /app

# Copy và install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -q -r requirements.txt

# Set Airflow env mặc định
ENV AIRFLOW_HOME=/tmp/airflow
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False